language: python
python:
- '2.7'
#cache the installed deps of the project
cache: pip 
install: pip install -r requirements.txt
script: 
- python test.py

notifications:
  webhooks:
    - http://posttestserver.com/post.php
